apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCTiUcWfIYc4+pOhVw2b9zMnP8AOAR1EY+1AFoPHV3GFucHoKEkKck/jJZ9pcbk+bwKS34go1d2yABEnr3h2XER0SMybfWgVA1XEUD4d7kVdMdi8LvSO8YQPeAkdHKILQO/ZO6N5N5Mnp1oaoZk/6hNBksf9xKbjfu4urSz1T3bznWMgEI43zhIiW2eCDPnJYaFOZr9IMG4vR4lqh7F5NoYA+cgW9lxlfMt3WyPyoEBUli0BstGVUHwPaF6jp2Sff0RVsonvWRXPCsrbxo8LwjgWOx5MayOjYnoAAWymUlXogA+/W5GKgrwYVfNBw2iZv6ZKNYDxogMiT7K4m1aBwnOeU4fFbQF4eBpbBw3+vZYv7CoY+r5qgow2LWxTmDzhb2yCgz0Xb8wKQtGaj8jYIw7aMHk/k5PedjWJ3QxnRikB+6iBcaW9goB3vOcZQ4V6+RORgVqdhl9Pmyc4cQxVMwE54Gw/zC8PB3yCnUWRoXfvJVWiuqiOuPy+bh0Pyv/9JREkXOxdaPyiidZg8n3yYj++I9eJ4J+QRQQbfY4wTVbtBYPaByB7t0CHoLZbL+NZDE8YktT++uiPaeSu1CsrSjLfMnlziHGgSIdqJQbe75+B+Zz4XTa/70dpraEsNDb8SXQx8kQ4eOs2x1OYogM2CQnRhwlb56zWCEewqY1fKXn6sZSB7ZQ05eqt8fU1lF1EwXzkNx/oosqklh9929KHP2rtgMkQw==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
