apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-new-env-bus
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgDPnI3yj2KIW8IIsvzvW7EA70QCOc7Y9nLZ7Ab7NKUOXExPgXXr7UhzRSVrrYveWNMZKshlHlq2kDci8Ra53ZIeVcB6BcvGxExiZ7udWpSSxhsa9+HnJiKGd8xitbXPMiPtb5m4eEnqX55oywxFJXlfL4qkLU9sMjWY27xHHtkZ0AG8d2J06dyAoAheAs4LUzMacxDa4JopMtzOltqXODo33UPFRHpfxyK7e+0IzwQk64LYbA9hWv9BtB0SOBbQMGjuj16971IIH1Qi4QfGUcVaG+6Wzh2HOuutMOwb/S5x/J4CSErtjHXAtse+FeOdPpYiyWSRLfB9GTo8FpIo91b1Oz7sfoWOjjKTDFSmPWl0TcRaaVimvF38bmMTvtnp05cLOR5toZ3e8zTrn0ODlPy8+0dK5B9TggYlx61YOqgi5pFmoOwl0znB/GiNkK4iB7Ll9KzyKRYUA0jU7sRKjmXmHsuDwoQ7o9/B43FUujSqDl+3oUfXBXFDvcXZdBT2FGyx631i/f0lCERopd+wRi0vuH8CgqrBZuwqvopTclBjhNJByzjwoQ2/evcqQxW0B4rpwtD4ZkSUyuC/MlSS5iBf81+PxtI0oUi3GNS2bJ/FQ7wMfAiE7bngRbgllEqA6A+C7JulSB/GaTTCOd3vYAMSFEC94f5+aWpYcuuoUXPoVHxwiE8ROSAs1YZcllWSJYw92IdI+lnKRYvmQ50nLU6AlVqH8w==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-new-env-bus
      namespace: cicd
    type: Opaque
