apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBgKu0hRGfgfXdCB7DL33ZwQKSsBdM/l8JCveMO5BAJSTnUPBxCaePB4G+5upT8nuNCG/8NG2u3eOLJInX6XBzOBUYpeV75YynBo/Y7mjLmD4gs0YZaonM0wvyR27/ZWGH2PM0wmqNpcenXzp9OYbgq7/itEUSKq+izFQtjc7v6RHz2Kuj3UkQDidn3dwRDyLULZxdfWEpAPBMFXxooKsMJC7QlfMG5RJ60MzBnC8oJdpf07O1O6vBI6SiHaayQuDGlOZ6kCxIqQDHLDlhScuHLLbrf6jj/jWO6zy454973ovjoMvodJHKu3KIG41nJd0sXxPTLWDYmf3lrFk3hU/QkR/qP7Uzfvaw89uJdjXJNpTsy2GqkyZij4Ol0Cw64YIbfReLyMKOKL4L66kY43LrVgc8O6jcMg4DTeX8aIn8KQ87JT/K5DGjWaAyN/v5NYAg22udubNbVG+EPGyZGOCouyr3E9o5NW6s3nmzoRdmdy73w6/4CuolSa6mLnr9Y14gOm4P2QOaYBfdWiLdsmavGvr8X8Qvfb6qGJizxPzKUt8JXN4ECn1vJBsop55cb72Gw4cbfs1BwDtlcGRboa8Jsms6bosbp/QBFh0ix4byh6dgnrVJMHbLBLlDDF+LhEVfsBxvyh3vTeEPHXkAQzw9DNnbe3OUHNRrnPWQtwuMmcbc89tQvUvVhRPk1BA3T8ew2JhqouuQh3DdN+dTbyY5xjBoSsw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
